### ISSUE TITLE
Doesn't work on Gatsby@2.25.0 or above

### ISSUE THREAD

**Issue by AbdallahAbis** [squer-solutions/gatsby-plugin-open-graph-images#12]
I have an existing `Gatsby` site that uses this plugin but after upgrading to `Gatsby@2.25.0` or later the plugin throws an error.
<img width="1462" alt="Screen Shot 2021-02-10 at 23 53 41" src="https://user-images.githubusercontent.com/59185227/107583542-590e3a00-6bfb-11eb-9d7d-4e4d3dbe2b83.png">

**Comment by duffleit** [comment]
could be fixed by https://github.com/squer-solutions/gatsby-plugin-open-graph-images/pull/9?
