### ISSUE TITLE
Doesn't generation image

### ISSUE THREAD

**Issue by KarkLeo** [squer-solutions/gatsby-plugin-open-graph-images#6]
Doesn't generate an image based on the component. 
Is there a component problem?
Perhaps you need a third-party image generator from markup?

It is not obvious what is in the `src/templates/artist-og-image.js` component from the [example](https://dev.to/duffleit/bridging-the-gap-between-gatsby-and-open-graph-images-52gh)

**Comment by neurosnap** [comment]
I'm not sure if you ran into the same issue I did, but I had to make a modification to how this plugin functioned.  You can try my fork here to see if it works for you: https://www.npmjs.com/package/gatsby-plugin-ogi

In particular, I had to comment this line out: https://github.com/neurosnap/gatsby-plugin-ogi/blob/master/src/generator.js#L22
